//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParallelProcess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=and-pc\\andb17,1433;Initial Catalog=LB_SWT;User ID=sa;Password=BimBam2" +
            "011;Persist Security Info=True;")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>1|APP|C:\\DEV\\SSG\\trunk\\Projects\\Util\\ParallelProcess\\TestWorker15\\bin\\Debu" +
            "g\\TestWorker15.exe</string>\r\n  <string>1|SQL|execute sp_endless</string>\r\n  <str" +
            "ing>1|SQL|execute sp_endless</string>\r\n  <string>1|APP|C:\\DEV\\SSG\\trunk\\Projects" +
            "\\Util\\ParallelProcess\\TestWorker15\\bin\\Debug\\TestWorker15.exe</string>\r\n  <strin" +
            "g>1|APP|C:\\DEV\\SSG\\trunk\\Projects\\Util\\ParallelProcess\\TestWorker15\\bin\\Debug\\Te" +
            "stWorker15.exe</string>\r\n  <string>2|APP|C:\\DEV\\SSG\\trunk\\Projects\\Util\\Parallel" +
            "Process\\TestWorker15\\bin\\Debug\\TestWorker15.exe</string>\r\n  <string>2|APP|C:\\DEV" +
            "\\SSG\\trunk\\Projects\\Util\\ParallelProcess\\TestWorker15\\bin\\Debug\\TestWorker15.exe" +
            "</string>\r\n  <string>1|APP|C:\\DEV\\SSG\\trunk\\Projects\\Util\\ParallelProcess\\TestWo" +
            "rker15\\bin\\Debug\\TestWorker15.exe</string>\r\n  <string>1|APP|C:\\DEV\\SSG\\trunk\\Pro" +
            "jects\\Util\\ParallelProcess\\TestWorker15\\bin\\Debug\\TestWorker15.exe</string>\r\n  <" +
            "string>1|APP|C:\\DEV\\SSG\\trunk\\Projects\\Util\\ParallelProcess\\TestWorker15\\bin\\Deb" +
            "ug\\TestWorker15.exe</string>\r\n  <string>1|APP|C:\\DEV\\SSG\\trunk\\Projects\\Util\\Par" +
            "allelProcess\\TestWorker15\\bin\\Debug\\TestWorker15.exe</string>\r\n  <string>1|APP|C" +
            ":\\DEV\\SSG\\trunk\\Projects\\Util\\ParallelProcess\\TestWorker15\\bin\\Debug\\TestWorker1" +
            "5.exe</string>\r\n  <string>1|APP|C:\\DEV\\SSG\\trunk\\Projects\\Util\\ParallelProcess\\T" +
            "estWorker15\\bin\\Debug\\TestWorker15.exe</string>\r\n  <string>3|APP|C:\\DEV\\SSG\\trun" +
            "k\\Projects\\Util\\ParallelProcess\\TestWorker15\\bin\\Debug\\TestWorker15.exe</string>" +
            "\r\n  <string>1|APP|C:\\DEV\\SSG\\trunk\\Projects\\Util\\ParallelProcess\\TestWorker15\\bi" +
            "n\\Debug\\TestWorker15.exe</string>\r\n  <string>1|APP|C:\\DEV\\SSG\\trunk\\Projects\\Uti" +
            "l\\ParallelProcess\\TestWorker15\\bin\\Debug\\TestWorker15.exe</string>\r\n  <string>1|" +
            "APP|C:\\DEV\\SSG\\trunk\\Projects\\Util\\ParallelProcess\\TestWorker15\\bin\\Debug\\TestWo" +
            "rker15.exe</string>\r\n  <string>1|APP|C:\\DEV\\SSG\\trunk\\Projects\\Util\\ParallelProc" +
            "ess\\TestWorker15\\bin\\Debug\\TestWorker15.exe</string>\r\n  <string>1|APP|C:\\DEV\\SSG" +
            "\\trunk\\Projects\\Util\\ParallelProcess\\TestWorker15\\bin\\Debug\\TestWorker15.exe</st" +
            "ring>\r\n  <string>1|APP|C:\\DEV\\SSG\\trunk\\Projects\\Util\\ParallelProcess\\TestWorker" +
            "15\\bin\\Debug\\TestWorker15.exe</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Prozesse {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Prozesse"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxProcess {
            get {
                return ((int)(this["MaxProcess"]));
            }
        }
    }
}
