//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18063
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Threading.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>D:\WorkerTest.exe</string>
  <string>D:\WorkerTest.exe</string>
  <string>D:\WorkerTest.exe</string>
  <string>D:\WorkerTest.exe</string>
  <string>D:\WorkerTest.exe</string>
  <string>D:\WorkerTest.exe</string>
  <string>D:\WorkerTest.exe</string>
  <string>D:\WorkerTest.exe</string>
  <string>D:\WorkerTest.exe</string>
  <string>D:\WorkerTest.exe</string>
  <string>D:\WorkerTest.exe</string>
  <string>D:\WorkerTest.exe</string>
  <string>D:\WorkerTest.exe</string>
  <string>D:\WorkerTest.exe</string>
  <string>D:\WorkerTest.exe</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Files {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Files"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxImport {
            get {
                return ((int)(this["MaxImport"]));
            }
        }
    }
}
